server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: qs707298


#eureka:
#  client:
#    service-url:  #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.demo.user.entity
  configuration:
    #是否开启自动驼峰命名规则映射：从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则Mybatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
   client:
      config:
         default:
            loggerLevel: FULL

