server:
  port: 1314
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr:  192.168.3.195:80 #nacos 地址
    gateway:
      routes: # 网关路由配置
        - id: movie-service #路由id, 自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 #路由的目标地址 http是固定地址
          uri: lb://movieService #路由的目标地址 lb就是负载均衡，后面是服务名称
          predicates: #路由断言，也就是判断是否符合路由规则的条件
             - Path=/movie/** #这个是按照路径匹配只要以 /movie 开头就符合要求
          filters:
             - AddRequestHeader=Truth, fuck