server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qs_movie?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: qs707298
#  application:
#    name: movieService #eureka的服务名称
#  profiles:
#    active: dev #开发环境，这里是的dev
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos服务地址
#      config:
#        file-extension: yaml #文件后缀名
#      discovery:
#        cluster-name: HZ
#        namespace: 265c862f-9c40-454e-91c8-be2d9c099d1c

#userservice: #要做配置的微服务的名称
#   ribbon:
#     NFloadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

#eureka:
#  client:
#    service-url:  #eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.demo.user.entity
  configuration:
    #是否开启自动驼峰命名规则映射：从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则Mybatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


feign:
#  client:
#    config:
#      default:
#        loggerLevel: NONE
  httpclient:
    enabled: true  #开启 feign 对httpClient的支持
    max-connections: 200  #最大连接数
    max-connections-per-route: 50 #每个路径的最大连接数

logging:
  level:
    demo.movie.clients.UserClient: debug
